FROM ghcr.io/astral-sh/uv:bookworm-slim

# This will be set by the GitHub action to the folder containing this component.
ARG FOLDER=/app

RUN mkdir /app && chown 1000:1000 /app

RUN mkdir -p /.cache/uv && chown -R 1000:1000 /.cache
RUN mkdir -p /.local/share/uv/python && chown -R 1000:1000 /.local/share/uv
RUN mkdir -p /.local/bin && chown -R 1000:1000 /.local/bin

WORKDIR /app

ENV UV_LINK_MODE=copy
ENV UV_PYTHON_INSTALL_DIR=$FOLDER/.python
ENV PATH="$FOLDER/.venv/bin:$PATH"

USER 1000:1000

CMD ["uv", "run", "--with", "uvicorn", "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--reload-dir", "src"]
